---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    login_cmd_template: 'bash'
    ansible_connection_options:
      connection: local
platforms:
  - name: localhost
lint:
  name: yamllint
provisioner:
  name: ansible
  env:
    MOLECULE_DEBUG: 'False'
    #  options:
    #    vvv: 'True'
  playbooks:
    converge: playbook.yml
  config_options:
    defaults:
      retry_files_enabled: 'False'
      ansible_connection: local
  inventory:
    host_vars:
      localhost:
        poly_custom_dirs:
          - polydir: '/opt'
            enabled: 'True'
            instance_prefix: '/opt/opt-inst'
            method: 'tmpfs'
            create: 'True'
            iscript: 'home'
            noinit: 'False'
            shared: 'False'
            mntopts: 'nodev,nosuid,noexec,ro'
            list_of_uids: ['root']
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
    connection: local
  lint:
    name: flake8
